wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.16.5
    framework: xgboost
    huggingface_version: 4.28.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713600950.0
    t:
      1:
      - 1
      - 5
      - 6
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 100
      3:
      - 13
      - 23
      4: 3.8.13
      5: 0.16.5
      6: 4.28.0
      8:
      - 5
      13: linux-x86_64
